services:

  portal:
    image: victoormorenoo/viaserra-portal:1.0-26174746
    ports:
      - "8046:80"
    restart: unless-stopped

  manutencao:
    build: manutencao/.
    ports:
      - "7046:80"
    restart: unless-stopped
